version: 0.0
os: linux
files:
  - source: ./test-deploy-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/deploy-me-app
  - source: ./deploy-me.yml
    destination: /home/ec2-user/deploy-me-app
permissions:
  - object: scripts
    pattern: "*.*"
    owner: ec2-user
    group: ec2-user
    mode: 700
    type:
      - file
hooks:
  ApplicationStart:
    - location: scripts/start-server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop-server
      timeout: 300
      runas: ec2-user

