version: 0.0
os: linux
files:
  - source: ./test-deploy-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/deploy-me-app
  - source: ./deploy-me.yml
    destination: /home/ec2-user/deploy-me-app
  - source: ./scripts
    destination: /home/ec2-user/deploy-me-app/scripts
permissions:
  - object: /home/ec2-user/deploy-me-app/scripts
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 700
    type:
      - file
hooks:
  ApplicationStart:
    - location: /home/ec2-user/deploy-me-app/scripts/start-server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: /home/ec2-user/deploy-me-app/scripts/stop-server
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: /home/ec2-user/deploy-me-app/scripts/verify
      timeout: 300
      runas: ec2-user